/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'Usuário De Acesso Ao Provedor',
		name: 'usuario',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
		required: true,
	},
	{
		displayName: 'Senha De Acesso Ao Provedor',
		name: 'senha',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
		typeOptions: { password: true },
		required: true,
	},
	{
		displayName: 'SITUACAO ESPECIAL',
		name: 'situacaoEspecial',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'TIPO',
		name: 'tipo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
		required: true,
	},
	{
		displayName: 'AMBIENTE',
		name: 'ambiente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'TELEFONE NUMERO',
		name: 'telefoneNumero',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'TELEFONE DDD',
		name: 'telefoneDdd',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SIT ESPECIAL MOTIVO',
		name: 'sitEspecialMotivo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SIT ESPECIAL DATA',
		name: 'sitEspecialData',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SIT CADASTRAL MOTIVO',
		name: 'sitCadastralMotivo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SIT CADASTRAL DATA',
		name: 'sitCadastralData',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SIT CADASTRAL CODIGO',
		name: 'sitCadastralCodigo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NAT JURIDICA DESCRICAO',
		name: 'natJuridicaDescricao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NAT JURIDICA CODIGO',
		name: 'natJuridicaCodigo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNAE DESCRICAO',
		name: 'cnaeDescricao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNAE CODIGO',
		name: 'cnaeCodigo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'ENTE FEDERATIVO',
		name: 'enteFederativo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DATA ABERTURA',
		name: 'dataAbertura',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CPF',
		name: 'cpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NOME',
		name: 'nome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DATA NASCIMENTO',
		name: 'dataNascimento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SEXO',
		name: 'sexo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'SITUACAO CPF',
		name: 'situacaoCpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NACIONALIDADE',
		name: 'nacionalidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNH CATEGORIA',
		name: 'cnhCategoria',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNH DATA PRIMEIRA HAB',
		name: 'cnhDataPrimeiraHab',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNH DATA VALIDADE',
		name: 'cnhDataValidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNH NUMERO REGISTRO',
		name: 'cnhNumeroRegistro',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DOC NUMERO',
		name: 'docNumero',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DOC ORGAO EXPEDIDOR',
		name: 'docOrgaoExpedidor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DOC TIPO',
		name: 'docTipo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'DOC UF EXPEDIDOR',
		name: 'docUfExpedidor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END BAIRRO',
		name: 'endBairro',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END CEP',
		name: 'endCep',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END COMPLEMENTO',
		name: 'endComplemento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END LOGRADOURO',
		name: 'endLogradouro',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END MUNICIPIO',
		name: 'endMunicipio',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END NUMERO',
		name: 'endNumero',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'END UF',
		name: 'endUf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'FILIACAO NOME MAE',
		name: 'filiacaoNomeMae',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'FILIACAO NOME PAI',
		name: 'filiacaoNomePai',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CNPJ',
		name: 'cnpj',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NOME FANTASIA',
		name: 'nomeFantasia',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'NOME ORGAO',
		name: 'nomeOrgao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'PORTE',
		name: 'porte',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'RAZAO SOCIAL',
		name: 'razaoSocial',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CAPITAL SOCIAL',
		name: 'capitalSocial',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
	{
		displayName: 'CORREIO ELETRONICO',
		name: 'correioEletronico',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_datavalid'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		usuario: this.getNodeParameter('usuario', i) as string,
		senha: this.getNodeParameter('senha', i) as string,
		SITUACAO_ESPECIAL: this.getNodeParameter('situacaoEspecial', i) as string,
		TIPO: this.getNodeParameter('tipo', i) as string,
		AMBIENTE: this.getNodeParameter('ambiente', i) as string,
		TELEFONE_NUMERO: this.getNodeParameter('telefoneNumero', i) as string,
		TELEFONE_DDD: this.getNodeParameter('telefoneDdd', i) as string,
		SIT_ESPECIAL_MOTIVO: this.getNodeParameter('sitEspecialMotivo', i) as string,
		SIT_ESPECIAL_DATA: this.getNodeParameter('sitEspecialData', i) as string,
		SIT_CADASTRAL_MOTIVO: this.getNodeParameter('sitCadastralMotivo', i) as string,
		SIT_CADASTRAL_DATA: this.getNodeParameter('sitCadastralData', i) as string,
		SIT_CADASTRAL_CODIGO: this.getNodeParameter('sitCadastralCodigo', i) as string,
		NAT_JURIDICA_DESCRICAO: this.getNodeParameter('natJuridicaDescricao', i) as string,
		NAT_JURIDICA_CODIGO: this.getNodeParameter('natJuridicaCodigo', i) as string,
		CNAE_DESCRICAO: this.getNodeParameter('cnaeDescricao', i) as string,
		CNAE_CODIGO: this.getNodeParameter('cnaeCodigo', i) as string,
		ENTE_FEDERATIVO: this.getNodeParameter('enteFederativo', i) as string,
		DATA_ABERTURA: this.getNodeParameter('dataAbertura', i) as string,
		CPF: this.getNodeParameter('cpf', i) as string,
		NOME: this.getNodeParameter('nome', i) as string,
		DATA_NASCIMENTO: this.getNodeParameter('dataNascimento', i) as string,
		SEXO: this.getNodeParameter('sexo', i) as string,
		SITUACAO_CPF: this.getNodeParameter('situacaoCpf', i) as string,
		NACIONALIDADE: this.getNodeParameter('nacionalidade', i) as string,
		CNH_CATEGORIA: this.getNodeParameter('cnhCategoria', i) as string,
		CNH_DATA_PRIMEIRA_HAB: this.getNodeParameter('cnhDataPrimeiraHab', i) as string,
		CNH_DATA_VALIDADE: this.getNodeParameter('cnhDataValidade', i) as string,
		CNH_NUMERO_REGISTRO: this.getNodeParameter('cnhNumeroRegistro', i) as string,
		DOC_NUMERO: this.getNodeParameter('docNumero', i) as string,
		DOC_ORGAO_EXPEDIDOR: this.getNodeParameter('docOrgaoExpedidor', i) as string,
		DOC_TIPO: this.getNodeParameter('docTipo', i) as string,
		DOC_UF_EXPEDIDOR: this.getNodeParameter('docUfExpedidor', i) as string,
		END_BAIRRO: this.getNodeParameter('endBairro', i) as string,
		END_CEP: this.getNodeParameter('endCep', i) as string,
		END_COMPLEMENTO: this.getNodeParameter('endComplemento', i) as string,
		END_LOGRADOURO: this.getNodeParameter('endLogradouro', i) as string,
		END_MUNICIPIO: this.getNodeParameter('endMunicipio', i) as string,
		END_NUMERO: this.getNodeParameter('endNumero', i) as string,
		END_UF: this.getNodeParameter('endUf', i) as string,
		FILIACAO_NOME_MAE: this.getNodeParameter('filiacaoNomeMae', i) as string,
		FILIACAO_NOME_PAI: this.getNodeParameter('filiacaoNomePai', i) as string,
		CNPJ: this.getNodeParameter('cnpj', i) as string,
		NOME_FANTASIA: this.getNodeParameter('nomeFantasia', i) as string,
		NOME_ORGAO: this.getNodeParameter('nomeOrgao', i) as string,
		PORTE: this.getNodeParameter('porte', i) as string,
		RAZAO_SOCIAL: this.getNodeParameter('razaoSocial', i) as string,
		CAPITAL_SOCIAL: this.getNodeParameter('capitalSocial', i) as string,
		CORREIO_ELETRONICO: this.getNodeParameter('correioEletronico', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'serpro_datavalid',
		parametros,
		webhookUrl,
	});
}
