/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Usuário De Acesso Ao Provedor',
		name: 'usuario',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
		required: true,
	},
	{
		displayName: 'Senha De Acesso Ao Provedor',
		name: 'senha',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
		typeOptions: { password: true },
		required: true,
	},
	{
		displayName: 'MODULODEDECISAO',
		name: 'modulodedecisao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'PARCELASEGURA',
		name: 'parcelasegura',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore10',
		name: 'modeloscore10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore09',
		name: 'modeloscore09',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore08',
		name: 'modeloscore08',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore07',
		name: 'modeloscore07',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore06',
		name: 'modeloscore06',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore05',
		name: 'modeloscore05',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore04',
		name: 'modeloscore04',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore03',
		name: 'modeloscore03',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore02',
		name: 'modeloscore02',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Modeloscore01',
		name: 'modeloscore01',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'SCORECREDITO',
		name: 'scorecredito',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'CEPDEORIGEM',
		name: 'cepdeorigem',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'TELEFONE',
		name: 'telefone',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'DDD',
		name: 'ddd',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'TIPODECREDITO',
		name: 'tipodecredito',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'VALOR',
		name: 'valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'QUANTIDADE',
		name: 'quantidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'DATADOCHEQUE',
		name: 'datadocheque',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Campo-3',
		name: 'campo3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Campo-2',
		name: 'campo2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'Campo-1',
		name: 'campo1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'DIGITOCH',
		name: 'digitoch',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'CHEQUE',
		name: 'cheque',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'DIGITOCC',
		name: 'digitocc',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'CONTACORRENTE',
		name: 'contacorrente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'AGENCIA',
		name: 'agencia',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'BANCO',
		name: 'banco',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'ORIGEMDASINFORMACOES',
		name: 'origemdasinformacoes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'NOME',
		name: 'nome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'CPF',
		name: 'cpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'TIPODEDOCUMENTO',
		name: 'tipodedocumento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'VERSAODACONSULTA',
		name: 'versaodaconsulta',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'CONSULTA',
		name: 'consulta',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
	{
		displayName: 'AMBIENTE',
		name: 'ambiente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['spc'], operation: ['scpc_acerta_pf'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		usuario: this.getNodeParameter('usuario', i) as string,
		senha: this.getNodeParameter('senha', i) as string,
		MODULODEDECISAO: this.getNodeParameter('modulodedecisao', i) as string,
		PARCELASEGURA: this.getNodeParameter('parcelasegura', i) as string,
		MODELOSCORE10: this.getNodeParameter('modeloscore10', i) as string,
		MODELOSCORE09: this.getNodeParameter('modeloscore09', i) as string,
		MODELOSCORE08: this.getNodeParameter('modeloscore08', i) as string,
		MODELOSCORE07: this.getNodeParameter('modeloscore07', i) as string,
		MODELOSCORE06: this.getNodeParameter('modeloscore06', i) as string,
		MODELOSCORE05: this.getNodeParameter('modeloscore05', i) as string,
		MODELOSCORE04: this.getNodeParameter('modeloscore04', i) as string,
		MODELOSCORE03: this.getNodeParameter('modeloscore03', i) as string,
		MODELOSCORE02: this.getNodeParameter('modeloscore02', i) as string,
		MODELOSCORE01: this.getNodeParameter('modeloscore01', i) as string,
		SCORECREDITO: this.getNodeParameter('scorecredito', i) as string,
		CEPDEORIGEM: this.getNodeParameter('cepdeorigem', i) as string,
		TELEFONE: this.getNodeParameter('telefone', i) as string,
		DDD: this.getNodeParameter('ddd', i) as string,
		TIPODECREDITO: this.getNodeParameter('tipodecredito', i) as string,
		VALOR: this.getNodeParameter('valor', i) as string,
		QUANTIDADE: this.getNodeParameter('quantidade', i) as string,
		DATADOCHEQUE: this.getNodeParameter('datadocheque', i) as string,
		'CAMPO-3': this.getNodeParameter('campo3', i) as string,
		'CAMPO-2': this.getNodeParameter('campo2', i) as string,
		'CAMPO-1': this.getNodeParameter('campo1', i) as string,
		DIGITOCH: this.getNodeParameter('digitoch', i) as string,
		CHEQUE: this.getNodeParameter('cheque', i) as string,
		DIGITOCC: this.getNodeParameter('digitocc', i) as string,
		CONTACORRENTE: this.getNodeParameter('contacorrente', i) as string,
		AGENCIA: this.getNodeParameter('agencia', i) as string,
		BANCO: this.getNodeParameter('banco', i) as string,
		ORIGEMDASINFORMACOES: this.getNodeParameter('origemdasinformacoes', i) as string,
		NOME: this.getNodeParameter('nome', i) as string,
		CPF: this.getNodeParameter('cpf', i) as string,
		TIPODEDOCUMENTO: this.getNodeParameter('tipodedocumento', i) as string,
		VERSAODACONSULTA: this.getNodeParameter('versaodaconsulta', i) as string,
		CONSULTA: this.getNodeParameter('consulta', i) as string,
		AMBIENTE: this.getNodeParameter('ambiente', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'scpc_acerta_pf',
		parametros,
		webhookUrl,
	});
}
