/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'Usuário De Acesso Ao Provedor',
		name: 'usuario',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
		required: true,
	},
	{
		displayName: 'Senha De Acesso Ao Provedor',
		name: 'senha',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
		typeOptions: { password: true },
		required: true,
	},
	{
		displayName: 'AMBIENTE',
		name: 'ambiente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'UID',
		name: 'uid',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'STATUS KYC',
		name: 'statusKyc',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'REPORT URL',
		name: 'reportUrl',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO SEVERITY',
		name: 'passedTrueInfoSeverity',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO CODE',
		name: 'passedTrueInfoCode',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 1',
		name: 'passedTrueInfoParam1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 1',
		name: 'passedTrueInfoValue1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 2',
		name: 'passedTrueInfoParam2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 2',
		name: 'passedTrueInfoValue2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 3',
		name: 'passedTrueInfoParam3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 3',
		name: 'passedTrueInfoValue3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 6',
		name: 'passedTrueWarnValue6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 6',
		name: 'passedTrueWarnParam6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 5',
		name: 'passedTrueWarnValue5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'TICKET KYC',
		name: 'ticketKyc',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 4',
		name: 'passedTrueInfoParam4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 4',
		name: 'passedTrueInfoValue4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 5',
		name: 'passedTrueInfoParam5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 5',
		name: 'passedTrueInfoValue5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 6',
		name: 'passedTrueInfoParam6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 6',
		name: 'passedTrueInfoValue6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 7',
		name: 'passedTrueInfoParam7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 3',
		name: 'passedTrueWarnParam3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 12',
		name: 'passedTrueWarnParam12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 7',
		name: 'passedTrueInfoValue7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 8',
		name: 'passedTrueInfoParam8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 8',
		name: 'passedTrueInfoValue8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 9',
		name: 'passedTrueInfoParam9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 9',
		name: 'passedTrueInfoValue9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 10',
		name: 'passedTrueInfoParam10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 10',
		name: 'passedTrueInfoValue10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 11',
		name: 'passedTrueInfoParam11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 11',
		name: 'passedTrueInfoValue11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 12',
		name: 'passedTrueInfoParam12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 12',
		name: 'passedTrueInfoValue12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 20',
		name: 'passedFalseErrorValue20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 20',
		name: 'passedFalseErrorParam20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 19',
		name: 'passedFalseErrorValue19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 19',
		name: 'passedFalseErrorParam19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 18',
		name: 'passedFalseErrorValue18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 5',
		name: 'passedTrueWarnParam5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 4',
		name: 'passedTrueWarnValue4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 4',
		name: 'passedTrueWarnParam4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 3',
		name: 'passedTrueWarnValue3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 18',
		name: 'passedFalseErrorParam18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 13',
		name: 'passedTrueInfoParam13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 17',
		name: 'passedFalseErrorValue17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 13',
		name: 'passedTrueInfoValue13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 14',
		name: 'passedTrueInfoParam14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 17',
		name: 'passedFalseErrorParam17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 16',
		name: 'passedFalseErrorValue16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 14',
		name: 'passedTrueInfoValue14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 15',
		name: 'passedTrueInfoParam15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 16',
		name: 'passedFalseErrorParam16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 15',
		name: 'passedTrueInfoValue15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 15',
		name: 'passedFalseErrorValue15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 15',
		name: 'passedFalseErrorParam15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 14',
		name: 'passedFalseErrorValue14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 14',
		name: 'passedFalseErrorParam14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 13',
		name: 'passedFalseErrorValue13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 13',
		name: 'passedFalseErrorParam13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 12',
		name: 'passedFalseErrorValue12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 16',
		name: 'passedTrueInfoParam16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 12',
		name: 'passedFalseErrorParam12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 11',
		name: 'passedFalseErrorValue11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 11',
		name: 'passedFalseErrorParam11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 10',
		name: 'passedFalseErrorValue10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 10',
		name: 'passedFalseErrorParam10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 9',
		name: 'passedFalseErrorValue9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 9',
		name: 'passedFalseErrorParam9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 8',
		name: 'passedFalseErrorValue8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 8',
		name: 'passedFalseErrorParam8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 7',
		name: 'passedFalseErrorValue7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 7',
		name: 'passedFalseErrorParam7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 6',
		name: 'passedFalseErrorValue6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 6',
		name: 'passedFalseErrorParam6',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 5',
		name: 'passedFalseErrorValue5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 5',
		name: 'passedFalseErrorParam5',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 4',
		name: 'passedFalseErrorValue4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 4',
		name: 'passedFalseErrorParam4',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 3',
		name: 'passedFalseErrorValue3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 3',
		name: 'passedFalseErrorParam3',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 2',
		name: 'passedFalseErrorValue2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 2',
		name: 'passedFalseErrorParam2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 18',
		name: 'passedTrueWarnValue18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 16',
		name: 'passedTrueInfoValue16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 17',
		name: 'passedTrueInfoParam17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 17',
		name: 'passedTrueInfoValue17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 18',
		name: 'passedTrueInfoParam18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR VALUE 1',
		name: 'passedFalseErrorValue1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 18',
		name: 'passedTrueInfoValue18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 19',
		name: 'passedTrueInfoParam19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 19',
		name: 'passedTrueInfoValue19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO PARAM 20',
		name: 'passedTrueInfoParam20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE INFO VALUE 20',
		name: 'passedTrueInfoValue20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN CODE',
		name: 'passedTrueWarnCode',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR PARAM 1',
		name: 'passedFalseErrorParam1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED FALSE ERROR CODE',
		name: 'passedFalseErrorCode',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 20',
		name: 'passedTrueWarnValue20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 20',
		name: 'passedTrueWarnParam20',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 19',
		name: 'passedTrueWarnValue19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 19',
		name: 'passedTrueWarnParam19',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 18',
		name: 'passedTrueWarnParam18',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 17',
		name: 'passedTrueWarnValue17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 17',
		name: 'passedTrueWarnParam17',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 16',
		name: 'passedTrueWarnValue16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 16',
		name: 'passedTrueWarnParam16',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 15',
		name: 'passedTrueWarnValue15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 15',
		name: 'passedTrueWarnParam15',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 14',
		name: 'passedTrueWarnValue14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 14',
		name: 'passedTrueWarnParam14',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 13',
		name: 'passedTrueWarnValue13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 13',
		name: 'passedTrueWarnParam13',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 12',
		name: 'passedTrueWarnValue12',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 1',
		name: 'passedTrueWarnParam1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 1',
		name: 'passedTrueWarnValue1',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 2',
		name: 'passedTrueWarnParam2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 2',
		name: 'passedTrueWarnValue2',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 11',
		name: 'passedTrueWarnValue11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 11',
		name: 'passedTrueWarnParam11',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 10',
		name: 'passedTrueWarnValue10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 10',
		name: 'passedTrueWarnParam10',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 9',
		name: 'passedTrueWarnValue9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 9',
		name: 'passedTrueWarnParam9',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 8',
		name: 'passedTrueWarnValue8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 8',
		name: 'passedTrueWarnParam8',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN VALUE 7',
		name: 'passedTrueWarnValue7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
	{
		displayName: 'PASSED TRUE WARN PARAM 7',
		name: 'passedTrueWarnParam7',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['bradesco'], operation: ['bradesco_kyc'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		usuario: this.getNodeParameter('usuario', i) as string,
		senha: this.getNodeParameter('senha', i) as string,
		AMBIENTE: this.getNodeParameter('ambiente', i) as string,
		UID: this.getNodeParameter('uid', i) as string,
		STATUS_KYC: this.getNodeParameter('statusKyc', i) as string,
		REPORT_URL: this.getNodeParameter('reportUrl', i) as string,
		PASSED_TRUE_INFO_SEVERITY: this.getNodeParameter('passedTrueInfoSeverity', i) as string,
		PASSED_TRUE_INFO_CODE: this.getNodeParameter('passedTrueInfoCode', i) as string,
		PASSED_TRUE_INFO_PARAM_1: this.getNodeParameter('passedTrueInfoParam1', i) as string,
		PASSED_TRUE_INFO_VALUE_1: this.getNodeParameter('passedTrueInfoValue1', i) as string,
		PASSED_TRUE_INFO_PARAM_2: this.getNodeParameter('passedTrueInfoParam2', i) as string,
		PASSED_TRUE_INFO_VALUE_2: this.getNodeParameter('passedTrueInfoValue2', i) as string,
		PASSED_TRUE_INFO_PARAM_3: this.getNodeParameter('passedTrueInfoParam3', i) as string,
		PASSED_TRUE_INFO_VALUE_3: this.getNodeParameter('passedTrueInfoValue3', i) as string,
		PASSED_TRUE_WARN_VALUE_6: this.getNodeParameter('passedTrueWarnValue6', i) as string,
		PASSED_TRUE_WARN_PARAM_6: this.getNodeParameter('passedTrueWarnParam6', i) as string,
		PASSED_TRUE_WARN_VALUE_5: this.getNodeParameter('passedTrueWarnValue5', i) as string,
		TICKET_KYC: this.getNodeParameter('ticketKyc', i) as string,
		PASSED_TRUE_INFO_PARAM_4: this.getNodeParameter('passedTrueInfoParam4', i) as string,
		PASSED_TRUE_INFO_VALUE_4: this.getNodeParameter('passedTrueInfoValue4', i) as string,
		PASSED_TRUE_INFO_PARAM_5: this.getNodeParameter('passedTrueInfoParam5', i) as string,
		PASSED_TRUE_INFO_VALUE_5: this.getNodeParameter('passedTrueInfoValue5', i) as string,
		PASSED_TRUE_INFO_PARAM_6: this.getNodeParameter('passedTrueInfoParam6', i) as string,
		PASSED_TRUE_INFO_VALUE_6: this.getNodeParameter('passedTrueInfoValue6', i) as string,
		PASSED_TRUE_INFO_PARAM_7: this.getNodeParameter('passedTrueInfoParam7', i) as string,
		PASSED_TRUE_WARN_PARAM_3: this.getNodeParameter('passedTrueWarnParam3', i) as string,
		PASSED_TRUE_WARN_PARAM_12: this.getNodeParameter('passedTrueWarnParam12', i) as string,
		PASSED_TRUE_INFO_VALUE_7: this.getNodeParameter('passedTrueInfoValue7', i) as string,
		PASSED_TRUE_INFO_PARAM_8: this.getNodeParameter('passedTrueInfoParam8', i) as string,
		PASSED_TRUE_INFO_VALUE_8: this.getNodeParameter('passedTrueInfoValue8', i) as string,
		PASSED_TRUE_INFO_PARAM_9: this.getNodeParameter('passedTrueInfoParam9', i) as string,
		PASSED_TRUE_INFO_VALUE_9: this.getNodeParameter('passedTrueInfoValue9', i) as string,
		PASSED_TRUE_INFO_PARAM_10: this.getNodeParameter('passedTrueInfoParam10', i) as string,
		PASSED_TRUE_INFO_VALUE_10: this.getNodeParameter('passedTrueInfoValue10', i) as string,
		PASSED_TRUE_INFO_PARAM_11: this.getNodeParameter('passedTrueInfoParam11', i) as string,
		PASSED_TRUE_INFO_VALUE_11: this.getNodeParameter('passedTrueInfoValue11', i) as string,
		PASSED_TRUE_INFO_PARAM_12: this.getNodeParameter('passedTrueInfoParam12', i) as string,
		PASSED_TRUE_INFO_VALUE_12: this.getNodeParameter('passedTrueInfoValue12', i) as string,
		PASSED_FALSE_ERROR_VALUE_20: this.getNodeParameter('passedFalseErrorValue20', i) as string,
		PASSED_FALSE_ERROR_PARAM_20: this.getNodeParameter('passedFalseErrorParam20', i) as string,
		PASSED_FALSE_ERROR_VALUE_19: this.getNodeParameter('passedFalseErrorValue19', i) as string,
		PASSED_FALSE_ERROR_PARAM_19: this.getNodeParameter('passedFalseErrorParam19', i) as string,
		PASSED_FALSE_ERROR_VALUE_18: this.getNodeParameter('passedFalseErrorValue18', i) as string,
		PASSED_TRUE_WARN_PARAM_5: this.getNodeParameter('passedTrueWarnParam5', i) as string,
		PASSED_TRUE_WARN_VALUE_4: this.getNodeParameter('passedTrueWarnValue4', i) as string,
		PASSED_TRUE_WARN_PARAM_4: this.getNodeParameter('passedTrueWarnParam4', i) as string,
		PASSED_TRUE_WARN_VALUE_3: this.getNodeParameter('passedTrueWarnValue3', i) as string,
		PASSED_FALSE_ERROR_PARAM_18: this.getNodeParameter('passedFalseErrorParam18', i) as string,
		PASSED_TRUE_INFO_PARAM_13: this.getNodeParameter('passedTrueInfoParam13', i) as string,
		PASSED_FALSE_ERROR_VALUE_17: this.getNodeParameter('passedFalseErrorValue17', i) as string,
		PASSED_TRUE_INFO_VALUE_13: this.getNodeParameter('passedTrueInfoValue13', i) as string,
		PASSED_TRUE_INFO_PARAM_14: this.getNodeParameter('passedTrueInfoParam14', i) as string,
		PASSED_FALSE_ERROR_PARAM_17: this.getNodeParameter('passedFalseErrorParam17', i) as string,
		PASSED_FALSE_ERROR_VALUE_16: this.getNodeParameter('passedFalseErrorValue16', i) as string,
		PASSED_TRUE_INFO_VALUE_14: this.getNodeParameter('passedTrueInfoValue14', i) as string,
		PASSED_TRUE_INFO_PARAM_15: this.getNodeParameter('passedTrueInfoParam15', i) as string,
		PASSED_FALSE_ERROR_PARAM_16: this.getNodeParameter('passedFalseErrorParam16', i) as string,
		PASSED_TRUE_INFO_VALUE_15: this.getNodeParameter('passedTrueInfoValue15', i) as string,
		PASSED_FALSE_ERROR_VALUE_15: this.getNodeParameter('passedFalseErrorValue15', i) as string,
		PASSED_FALSE_ERROR_PARAM_15: this.getNodeParameter('passedFalseErrorParam15', i) as string,
		PASSED_FALSE_ERROR_VALUE_14: this.getNodeParameter('passedFalseErrorValue14', i) as string,
		PASSED_FALSE_ERROR_PARAM_14: this.getNodeParameter('passedFalseErrorParam14', i) as string,
		PASSED_FALSE_ERROR_VALUE_13: this.getNodeParameter('passedFalseErrorValue13', i) as string,
		PASSED_FALSE_ERROR_PARAM_13: this.getNodeParameter('passedFalseErrorParam13', i) as string,
		PASSED_FALSE_ERROR_VALUE_12: this.getNodeParameter('passedFalseErrorValue12', i) as string,
		PASSED_TRUE_INFO_PARAM_16: this.getNodeParameter('passedTrueInfoParam16', i) as string,
		PASSED_FALSE_ERROR_PARAM_12: this.getNodeParameter('passedFalseErrorParam12', i) as string,
		PASSED_FALSE_ERROR_VALUE_11: this.getNodeParameter('passedFalseErrorValue11', i) as string,
		PASSED_FALSE_ERROR_PARAM_11: this.getNodeParameter('passedFalseErrorParam11', i) as string,
		PASSED_FALSE_ERROR_VALUE_10: this.getNodeParameter('passedFalseErrorValue10', i) as string,
		PASSED_FALSE_ERROR_PARAM_10: this.getNodeParameter('passedFalseErrorParam10', i) as string,
		PASSED_FALSE_ERROR_VALUE_9: this.getNodeParameter('passedFalseErrorValue9', i) as string,
		PASSED_FALSE_ERROR_PARAM_9: this.getNodeParameter('passedFalseErrorParam9', i) as string,
		PASSED_FALSE_ERROR_VALUE_8: this.getNodeParameter('passedFalseErrorValue8', i) as string,
		PASSED_FALSE_ERROR_PARAM_8: this.getNodeParameter('passedFalseErrorParam8', i) as string,
		PASSED_FALSE_ERROR_VALUE_7: this.getNodeParameter('passedFalseErrorValue7', i) as string,
		PASSED_FALSE_ERROR_PARAM_7: this.getNodeParameter('passedFalseErrorParam7', i) as string,
		PASSED_FALSE_ERROR_VALUE_6: this.getNodeParameter('passedFalseErrorValue6', i) as string,
		PASSED_FALSE_ERROR_PARAM_6: this.getNodeParameter('passedFalseErrorParam6', i) as string,
		PASSED_FALSE_ERROR_VALUE_5: this.getNodeParameter('passedFalseErrorValue5', i) as string,
		PASSED_FALSE_ERROR_PARAM_5: this.getNodeParameter('passedFalseErrorParam5', i) as string,
		PASSED_FALSE_ERROR_VALUE_4: this.getNodeParameter('passedFalseErrorValue4', i) as string,
		PASSED_FALSE_ERROR_PARAM_4: this.getNodeParameter('passedFalseErrorParam4', i) as string,
		PASSED_FALSE_ERROR_VALUE_3: this.getNodeParameter('passedFalseErrorValue3', i) as string,
		PASSED_FALSE_ERROR_PARAM_3: this.getNodeParameter('passedFalseErrorParam3', i) as string,
		PASSED_FALSE_ERROR_VALUE_2: this.getNodeParameter('passedFalseErrorValue2', i) as string,
		PASSED_FALSE_ERROR_PARAM_2: this.getNodeParameter('passedFalseErrorParam2', i) as string,
		PASSED_TRUE_WARN_VALUE_18: this.getNodeParameter('passedTrueWarnValue18', i) as string,
		PASSED_TRUE_INFO_VALUE_16: this.getNodeParameter('passedTrueInfoValue16', i) as string,
		PASSED_TRUE_INFO_PARAM_17: this.getNodeParameter('passedTrueInfoParam17', i) as string,
		PASSED_TRUE_INFO_VALUE_17: this.getNodeParameter('passedTrueInfoValue17', i) as string,
		PASSED_TRUE_INFO_PARAM_18: this.getNodeParameter('passedTrueInfoParam18', i) as string,
		PASSED_FALSE_ERROR_VALUE_1: this.getNodeParameter('passedFalseErrorValue1', i) as string,
		PASSED_TRUE_INFO_VALUE_18: this.getNodeParameter('passedTrueInfoValue18', i) as string,
		PASSED_TRUE_INFO_PARAM_19: this.getNodeParameter('passedTrueInfoParam19', i) as string,
		PASSED_TRUE_INFO_VALUE_19: this.getNodeParameter('passedTrueInfoValue19', i) as string,
		PASSED_TRUE_INFO_PARAM_20: this.getNodeParameter('passedTrueInfoParam20', i) as string,
		PASSED_TRUE_INFO_VALUE_20: this.getNodeParameter('passedTrueInfoValue20', i) as string,
		PASSED_TRUE_WARN_CODE: this.getNodeParameter('passedTrueWarnCode', i) as string,
		PASSED_FALSE_ERROR_PARAM_1: this.getNodeParameter('passedFalseErrorParam1', i) as string,
		PASSED_FALSE_ERROR_CODE: this.getNodeParameter('passedFalseErrorCode', i) as string,
		PASSED_TRUE_WARN_VALUE_20: this.getNodeParameter('passedTrueWarnValue20', i) as string,
		PASSED_TRUE_WARN_PARAM_20: this.getNodeParameter('passedTrueWarnParam20', i) as string,
		PASSED_TRUE_WARN_VALUE_19: this.getNodeParameter('passedTrueWarnValue19', i) as string,
		PASSED_TRUE_WARN_PARAM_19: this.getNodeParameter('passedTrueWarnParam19', i) as string,
		PASSED_TRUE_WARN_PARAM_18: this.getNodeParameter('passedTrueWarnParam18', i) as string,
		PASSED_TRUE_WARN_VALUE_17: this.getNodeParameter('passedTrueWarnValue17', i) as string,
		PASSED_TRUE_WARN_PARAM_17: this.getNodeParameter('passedTrueWarnParam17', i) as string,
		PASSED_TRUE_WARN_VALUE_16: this.getNodeParameter('passedTrueWarnValue16', i) as string,
		PASSED_TRUE_WARN_PARAM_16: this.getNodeParameter('passedTrueWarnParam16', i) as string,
		PASSED_TRUE_WARN_VALUE_15: this.getNodeParameter('passedTrueWarnValue15', i) as string,
		PASSED_TRUE_WARN_PARAM_15: this.getNodeParameter('passedTrueWarnParam15', i) as string,
		PASSED_TRUE_WARN_VALUE_14: this.getNodeParameter('passedTrueWarnValue14', i) as string,
		PASSED_TRUE_WARN_PARAM_14: this.getNodeParameter('passedTrueWarnParam14', i) as string,
		PASSED_TRUE_WARN_VALUE_13: this.getNodeParameter('passedTrueWarnValue13', i) as string,
		PASSED_TRUE_WARN_PARAM_13: this.getNodeParameter('passedTrueWarnParam13', i) as string,
		PASSED_TRUE_WARN_VALUE_12: this.getNodeParameter('passedTrueWarnValue12', i) as string,
		PASSED_TRUE_WARN_PARAM_1: this.getNodeParameter('passedTrueWarnParam1', i) as string,
		PASSED_TRUE_WARN_VALUE_1: this.getNodeParameter('passedTrueWarnValue1', i) as string,
		PASSED_TRUE_WARN_PARAM_2: this.getNodeParameter('passedTrueWarnParam2', i) as string,
		PASSED_TRUE_WARN_VALUE_2: this.getNodeParameter('passedTrueWarnValue2', i) as string,
		PASSED_TRUE_WARN_VALUE_11: this.getNodeParameter('passedTrueWarnValue11', i) as string,
		PASSED_TRUE_WARN_PARAM_11: this.getNodeParameter('passedTrueWarnParam11', i) as string,
		PASSED_TRUE_WARN_VALUE_10: this.getNodeParameter('passedTrueWarnValue10', i) as string,
		PASSED_TRUE_WARN_PARAM_10: this.getNodeParameter('passedTrueWarnParam10', i) as string,
		PASSED_TRUE_WARN_VALUE_9: this.getNodeParameter('passedTrueWarnValue9', i) as string,
		PASSED_TRUE_WARN_PARAM_9: this.getNodeParameter('passedTrueWarnParam9', i) as string,
		PASSED_TRUE_WARN_VALUE_8: this.getNodeParameter('passedTrueWarnValue8', i) as string,
		PASSED_TRUE_WARN_PARAM_8: this.getNodeParameter('passedTrueWarnParam8', i) as string,
		PASSED_TRUE_WARN_VALUE_7: this.getNodeParameter('passedTrueWarnValue7', i) as string,
		PASSED_TRUE_WARN_PARAM_7: this.getNodeParameter('passedTrueWarnParam7', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'bradesco_kyc',
		parametros,
		webhookUrl,
	});
}
