/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Usuário De Acesso Ao Provedor',
		name: 'usuario',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		required: true,
	},
	{
		displayName: 'Senha De Acesso Ao Provedor',
		name: 'senha',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		typeOptions: { password: true },
		required: true,
	},
	{
		displayName: 'Cnpj Cpf',
		name: 'cnpjCpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		required: true,
	},
	{
		displayName: 'Prazo Meses',
		name: 'prazoMeses',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Forma Pagamento',
		name: 'formaPagamento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Codigo Proposta Cliente',
		name: 'codigoPropostaCliente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		required: true,
	},
	{
		displayName: 'Codigo Instituicao',
		name: 'codigoInstituicao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		required: true,
	},
	{
		displayName: 'Ddd',
		name: 'ddd',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Nacionalidade ID',
		name: 'nacionalidadeId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Nacionalidade Codigo',
		name: 'nacionalidadeCodigo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
		placeholder: 'name@email.com',
	},
	{
		displayName: 'Data Fundacao',
		name: 'dataFundacao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Razao Social',
		name: 'razaoSocial',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Nome Fantasia',
		name: 'nomeFantasia',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Data Nascimento',
		name: 'dataNascimento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Nome Mae',
		name: 'nomeMae',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Nome',
		name: 'nome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Valor Solicitado',
		name: 'valorSolicitado',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Ambiente',
		name: 'ambiente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Info Grupo Valor',
		name: 'infoGrupoValor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Info Grupo Nome',
		name: 'infoGrupoNome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Info Grupo',
		name: 'infoGrupo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Tipo Endereco',
		name: 'tipoEndereco',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Uf',
		name: 'uf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Numero',
		name: 'numero',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Logradouro',
		name: 'logradouro',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Complemento',
		name: 'complemento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Cidade',
		name: 'cidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Cep',
		name: 'cep',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Bairro',
		name: 'bairro',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Tipo Telefone',
		name: 'tipoTelefone',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Ramal',
		name: 'ramal',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
	{
		displayName: 'Telefone',
		name: 'telefone',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['alloha'], operation: ['alloha_b2e_envio_proposta'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		usuario: this.getNodeParameter('usuario', i) as string,
		senha: this.getNodeParameter('senha', i) as string,
		CNPJ_CPF: this.getNodeParameter('cnpjCpf', i) as string,
		PRAZO_MESES: this.getNodeParameter('prazoMeses', i) as string,
		FORMA_PAGAMENTO: this.getNodeParameter('formaPagamento', i) as string,
		CODIGO_PROPOSTA_CLIENTE: this.getNodeParameter('codigoPropostaCliente', i) as string,
		CODIGO_INSTITUICAO: this.getNodeParameter('codigoInstituicao', i) as string,
		DDD: this.getNodeParameter('ddd', i) as string,
		NACIONALIDADE_ID: this.getNodeParameter('nacionalidadeId', i) as string,
		NACIONALIDADE_CODIGO: this.getNodeParameter('nacionalidadeCodigo', i) as string,
		EMAIL: this.getNodeParameter('email', i) as string,
		DATA_FUNDACAO: this.getNodeParameter('dataFundacao', i) as string,
		RAZAO_SOCIAL: this.getNodeParameter('razaoSocial', i) as string,
		NOME_FANTASIA: this.getNodeParameter('nomeFantasia', i) as string,
		DATA_NASCIMENTO: this.getNodeParameter('dataNascimento', i) as string,
		NOME_MAE: this.getNodeParameter('nomeMae', i) as string,
		NOME: this.getNodeParameter('nome', i) as string,
		VALOR_SOLICITADO: this.getNodeParameter('valorSolicitado', i) as string,
		AMBIENTE: this.getNodeParameter('ambiente', i) as string,
		INFO_GRUPO_VALOR: this.getNodeParameter('infoGrupoValor', i) as string,
		INFO_GRUPO_NOME: this.getNodeParameter('infoGrupoNome', i) as string,
		INFO_GRUPO: this.getNodeParameter('infoGrupo', i) as string,
		TIPO_ENDERECO: this.getNodeParameter('tipoEndereco', i) as string,
		UF: this.getNodeParameter('uf', i) as string,
		NUMERO: this.getNodeParameter('numero', i) as string,
		LOGRADOURO: this.getNodeParameter('logradouro', i) as string,
		COMPLEMENTO: this.getNodeParameter('complemento', i) as string,
		CIDADE: this.getNodeParameter('cidade', i) as string,
		CEP: this.getNodeParameter('cep', i) as string,
		BAIRRO: this.getNodeParameter('bairro', i) as string,
		TIPO_TELEFONE: this.getNodeParameter('tipoTelefone', i) as string,
		RAMAL: this.getNodeParameter('ramal', i) as string,
		TELEFONE: this.getNodeParameter('telefone', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'alloha_b2e_envio_proposta',
		parametros,
		webhookUrl,
	});
}
