/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt15 VALOR',
		name: 'ipt15Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt16 CAMPO',
		name: 'ipt16Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt16 VALOR',
		name: 'ipt16Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt17 CAMPO',
		name: 'ipt17Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt17 VALOR',
		name: 'ipt17Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt18 CAMPO',
		name: 'ipt18Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt18 VALOR',
		name: 'ipt18Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt19 CAMPO',
		name: 'ipt19Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt19 VALOR',
		name: 'ipt19Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt20 CAMPO',
		name: 'ipt20Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt20 VALOR',
		name: 'ipt20Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt21 CAMPO',
		name: 'ipt21Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt21 VALOR',
		name: 'ipt21Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt22 CAMPO',
		name: 'ipt22Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt22 VALOR',
		name: 'ipt22Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt23 CAMPO',
		name: 'ipt23Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt23 VALOR',
		name: 'ipt23Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt24 CAMPO',
		name: 'ipt24Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt24 VALOR',
		name: 'ipt24Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt25 CAMPO',
		name: 'ipt25Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt25 VALOR',
		name: 'ipt25Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt26 CAMPO',
		name: 'ipt26Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt26 VALOR',
		name: 'ipt26Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt27 CAMPO',
		name: 'ipt27Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt27 VALOR',
		name: 'ipt27Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt28 CAMPO',
		name: 'ipt28Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt28 VALOR',
		name: 'ipt28Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt29 CAMPO',
		name: 'ipt29Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt29 VALOR',
		name: 'ipt29Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt30 CAMPO',
		name: 'ipt30Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt36 CAMPO',
		name: 'ipt36Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt35 VALOR',
		name: 'ipt35Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt35 CAMPO',
		name: 'ipt35Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt34 VALOR',
		name: 'ipt34Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt34 CAMPO',
		name: 'ipt34Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt33 VALOR',
		name: 'ipt33Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt33 CAMPO',
		name: 'ipt33Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt32 VALOR',
		name: 'ipt32Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt50 VALOR',
		name: 'ipt50Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt32 CAMPO',
		name: 'ipt32Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt31 VALOR',
		name: 'ipt31Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt31 CAMPO',
		name: 'ipt31Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt30 VALOR',
		name: 'ipt30Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt50 CAMPO',
		name: 'ipt50Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt49 VALOR',
		name: 'ipt49Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt49 CAMPO',
		name: 'ipt49Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt48 VALOR',
		name: 'ipt48Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt48 CAMPO',
		name: 'ipt48Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt47 VALOR',
		name: 'ipt47Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt47 CAMPO',
		name: 'ipt47Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt46 VALOR',
		name: 'ipt46Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt46 CAMPO',
		name: 'ipt46Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt45 VALOR',
		name: 'ipt45Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt45 CAMPO',
		name: 'ipt45Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt44 VALOR',
		name: 'ipt44Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt44 CAMPO',
		name: 'ipt44Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt43 VALOR',
		name: 'ipt43Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt43 CAMPO',
		name: 'ipt43Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt42 VALOR',
		name: 'ipt42Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt42 CAMPO',
		name: 'ipt42Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt41 VALOR',
		name: 'ipt41Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt41 CAMPO',
		name: 'ipt41Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt40 VALOR',
		name: 'ipt40Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt40 CAMPO',
		name: 'ipt40Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt39 VALOR',
		name: 'ipt39Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt39 CAMPO',
		name: 'ipt39Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt38 VALOR',
		name: 'ipt38Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt38 CAMPO',
		name: 'ipt38Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt37 VALOR',
		name: 'ipt37Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt37 CAMPO',
		name: 'ipt37Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt36 VALOR',
		name: 'ipt36Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt1 CAMPO',
		name: 'ipt1Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt1 VALOR',
		name: 'ipt1Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt2 CAMPO',
		name: 'ipt2Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt2 VALOR',
		name: 'ipt2Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt3 CAMPO',
		name: 'ipt3Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt3 VALOR',
		name: 'ipt3Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt4 CAMPO',
		name: 'ipt4Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt4 VALOR',
		name: 'ipt4Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt5 CAMPO',
		name: 'ipt5Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt5 VALOR',
		name: 'ipt5Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt6 CAMPO',
		name: 'ipt6Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt6 VALOR',
		name: 'ipt6Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt7 CAMPO',
		name: 'ipt7Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt7 VALOR',
		name: 'ipt7Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt8 CAMPO',
		name: 'ipt8Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt8 VALOR',
		name: 'ipt8Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt9 CAMPO',
		name: 'ipt9Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt9 VALOR',
		name: 'ipt9Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt10 CAMPO',
		name: 'ipt10Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt10 VALOR',
		name: 'ipt10Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt11 CAMPO',
		name: 'ipt11Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt11 VALOR',
		name: 'ipt11Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt12 CAMPO',
		name: 'ipt12Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt12 VALOR',
		name: 'ipt12Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt13 CAMPO',
		name: 'ipt13Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt13 VALOR',
		name: 'ipt13Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt14 CAMPO',
		name: 'ipt14Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt14 VALOR',
		name: 'ipt14Valor',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
	{
		displayName: 'Ipt15 CAMPO',
		name: 'ipt15Campo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['cm_software'], operation: ['dados_input_fluxo_csj'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		IPT15_VALOR: this.getNodeParameter('ipt15Valor', i) as string,
		IPT16_CAMPO: this.getNodeParameter('ipt16Campo', i) as string,
		IPT16_VALOR: this.getNodeParameter('ipt16Valor', i) as string,
		IPT17_CAMPO: this.getNodeParameter('ipt17Campo', i) as string,
		IPT17_VALOR: this.getNodeParameter('ipt17Valor', i) as string,
		IPT18_CAMPO: this.getNodeParameter('ipt18Campo', i) as string,
		IPT18_VALOR: this.getNodeParameter('ipt18Valor', i) as string,
		IPT19_CAMPO: this.getNodeParameter('ipt19Campo', i) as string,
		IPT19_VALOR: this.getNodeParameter('ipt19Valor', i) as string,
		IPT20_CAMPO: this.getNodeParameter('ipt20Campo', i) as string,
		IPT20_VALOR: this.getNodeParameter('ipt20Valor', i) as string,
		IPT21_CAMPO: this.getNodeParameter('ipt21Campo', i) as string,
		IPT21_VALOR: this.getNodeParameter('ipt21Valor', i) as string,
		IPT22_CAMPO: this.getNodeParameter('ipt22Campo', i) as string,
		IPT22_VALOR: this.getNodeParameter('ipt22Valor', i) as string,
		IPT23_CAMPO: this.getNodeParameter('ipt23Campo', i) as string,
		IPT23_VALOR: this.getNodeParameter('ipt23Valor', i) as string,
		IPT24_CAMPO: this.getNodeParameter('ipt24Campo', i) as string,
		IPT24_VALOR: this.getNodeParameter('ipt24Valor', i) as string,
		IPT25_CAMPO: this.getNodeParameter('ipt25Campo', i) as string,
		IPT25_VALOR: this.getNodeParameter('ipt25Valor', i) as string,
		IPT26_CAMPO: this.getNodeParameter('ipt26Campo', i) as string,
		IPT26_VALOR: this.getNodeParameter('ipt26Valor', i) as string,
		IPT27_CAMPO: this.getNodeParameter('ipt27Campo', i) as string,
		IPT27_VALOR: this.getNodeParameter('ipt27Valor', i) as string,
		IPT28_CAMPO: this.getNodeParameter('ipt28Campo', i) as string,
		IPT28_VALOR: this.getNodeParameter('ipt28Valor', i) as string,
		IPT29_CAMPO: this.getNodeParameter('ipt29Campo', i) as string,
		IPT29_VALOR: this.getNodeParameter('ipt29Valor', i) as string,
		IPT30_CAMPO: this.getNodeParameter('ipt30Campo', i) as string,
		IPT36_CAMPO: this.getNodeParameter('ipt36Campo', i) as string,
		IPT35_VALOR: this.getNodeParameter('ipt35Valor', i) as string,
		IPT35_CAMPO: this.getNodeParameter('ipt35Campo', i) as string,
		IPT34_VALOR: this.getNodeParameter('ipt34Valor', i) as string,
		IPT34_CAMPO: this.getNodeParameter('ipt34Campo', i) as string,
		IPT33_VALOR: this.getNodeParameter('ipt33Valor', i) as string,
		IPT33_CAMPO: this.getNodeParameter('ipt33Campo', i) as string,
		IPT32_VALOR: this.getNodeParameter('ipt32Valor', i) as string,
		IPT50_VALOR: this.getNodeParameter('ipt50Valor', i) as string,
		IPT32_CAMPO: this.getNodeParameter('ipt32Campo', i) as string,
		ID: this.getNodeParameter('id', i) as string,
		IPT31_VALOR: this.getNodeParameter('ipt31Valor', i) as string,
		IPT31_CAMPO: this.getNodeParameter('ipt31Campo', i) as string,
		IPT30_VALOR: this.getNodeParameter('ipt30Valor', i) as string,
		IPT50_CAMPO: this.getNodeParameter('ipt50Campo', i) as string,
		IPT49_VALOR: this.getNodeParameter('ipt49Valor', i) as string,
		IPT49_CAMPO: this.getNodeParameter('ipt49Campo', i) as string,
		IPT48_VALOR: this.getNodeParameter('ipt48Valor', i) as string,
		IPT48_CAMPO: this.getNodeParameter('ipt48Campo', i) as string,
		IPT47_VALOR: this.getNodeParameter('ipt47Valor', i) as string,
		IPT47_CAMPO: this.getNodeParameter('ipt47Campo', i) as string,
		IPT46_VALOR: this.getNodeParameter('ipt46Valor', i) as string,
		IPT46_CAMPO: this.getNodeParameter('ipt46Campo', i) as string,
		IPT45_VALOR: this.getNodeParameter('ipt45Valor', i) as string,
		IPT45_CAMPO: this.getNodeParameter('ipt45Campo', i) as string,
		IPT44_VALOR: this.getNodeParameter('ipt44Valor', i) as string,
		IPT44_CAMPO: this.getNodeParameter('ipt44Campo', i) as string,
		IPT43_VALOR: this.getNodeParameter('ipt43Valor', i) as string,
		IPT43_CAMPO: this.getNodeParameter('ipt43Campo', i) as string,
		IPT42_VALOR: this.getNodeParameter('ipt42Valor', i) as string,
		IPT42_CAMPO: this.getNodeParameter('ipt42Campo', i) as string,
		IPT41_VALOR: this.getNodeParameter('ipt41Valor', i) as string,
		IPT41_CAMPO: this.getNodeParameter('ipt41Campo', i) as string,
		IPT40_VALOR: this.getNodeParameter('ipt40Valor', i) as string,
		IPT40_CAMPO: this.getNodeParameter('ipt40Campo', i) as string,
		IPT39_VALOR: this.getNodeParameter('ipt39Valor', i) as string,
		IPT39_CAMPO: this.getNodeParameter('ipt39Campo', i) as string,
		IPT38_VALOR: this.getNodeParameter('ipt38Valor', i) as string,
		IPT38_CAMPO: this.getNodeParameter('ipt38Campo', i) as string,
		IPT37_VALOR: this.getNodeParameter('ipt37Valor', i) as string,
		IPT37_CAMPO: this.getNodeParameter('ipt37Campo', i) as string,
		IPT36_VALOR: this.getNodeParameter('ipt36Valor', i) as string,
		IPT1_CAMPO: this.getNodeParameter('ipt1Campo', i) as string,
		IPT1_VALOR: this.getNodeParameter('ipt1Valor', i) as string,
		IPT2_CAMPO: this.getNodeParameter('ipt2Campo', i) as string,
		IPT2_VALOR: this.getNodeParameter('ipt2Valor', i) as string,
		IPT3_CAMPO: this.getNodeParameter('ipt3Campo', i) as string,
		IPT3_VALOR: this.getNodeParameter('ipt3Valor', i) as string,
		IPT4_CAMPO: this.getNodeParameter('ipt4Campo', i) as string,
		IPT4_VALOR: this.getNodeParameter('ipt4Valor', i) as string,
		IPT5_CAMPO: this.getNodeParameter('ipt5Campo', i) as string,
		IPT5_VALOR: this.getNodeParameter('ipt5Valor', i) as string,
		IPT6_CAMPO: this.getNodeParameter('ipt6Campo', i) as string,
		IPT6_VALOR: this.getNodeParameter('ipt6Valor', i) as string,
		IPT7_CAMPO: this.getNodeParameter('ipt7Campo', i) as string,
		IPT7_VALOR: this.getNodeParameter('ipt7Valor', i) as string,
		IPT8_CAMPO: this.getNodeParameter('ipt8Campo', i) as string,
		IPT8_VALOR: this.getNodeParameter('ipt8Valor', i) as string,
		IPT9_CAMPO: this.getNodeParameter('ipt9Campo', i) as string,
		IPT9_VALOR: this.getNodeParameter('ipt9Valor', i) as string,
		IPT10_CAMPO: this.getNodeParameter('ipt10Campo', i) as string,
		IPT10_VALOR: this.getNodeParameter('ipt10Valor', i) as string,
		IPT11_CAMPO: this.getNodeParameter('ipt11Campo', i) as string,
		IPT11_VALOR: this.getNodeParameter('ipt11Valor', i) as string,
		IPT12_CAMPO: this.getNodeParameter('ipt12Campo', i) as string,
		IPT12_VALOR: this.getNodeParameter('ipt12Valor', i) as string,
		IPT13_CAMPO: this.getNodeParameter('ipt13Campo', i) as string,
		IPT13_VALOR: this.getNodeParameter('ipt13Valor', i) as string,
		IPT14_CAMPO: this.getNodeParameter('ipt14Campo', i) as string,
		IPT14_VALOR: this.getNodeParameter('ipt14Valor', i) as string,
		IPT15_CAMPO: this.getNodeParameter('ipt15Campo', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'dados_input_fluxo_csj',
		parametros,
		webhookUrl,
	});
}
