/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'Usuário De Acesso Ao Provedor',
		name: 'usuario',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
		required: true,
	},
	{
		displayName: 'Senha De Acesso Ao Provedor',
		name: 'senha',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
		typeOptions: { password: true },
		required: true,
	},
	{
		displayName: 'EMAIL',
		name: 'email',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
		placeholder: 'name@email.com',
	},
	{
		displayName: 'CPF V CONTEXTO',
		name: 'cpfVContexto',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CPF V INPUT',
		name: 'cpfVInput',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'IDWORKPROCESSO INPUT',
		name: 'idworkprocessoInput',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'TICKET INPUT',
		name: 'ticketInput',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'HASH INPUT',
		name: 'hashInput',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'VALOR PATRIMONIO',
		name: 'valorPatrimonio',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'UF RG',
		name: 'ufRg',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'UF RES',
		name: 'ufRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'UF COM',
		name: 'ufCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'TELEFONE RES',
		name: 'telefoneRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'TELEFONE COM',
		name: 'telefoneCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'TELEFONE CEL',
		name: 'telefoneCel',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'SEXO',
		name: 'sexo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'RENDA',
		name: 'renda',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'PROFISSAO',
		name: 'profissao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'ORGAO RG',
		name: 'orgaoRg',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NUMERO SEGURANCA CNH',
		name: 'numeroSegurancaCnh',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NUMERO RG',
		name: 'numeroRg',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NUMERO RES',
		name: 'numeroRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NUMERO REGISTRO CNH',
		name: 'numeroRegistroCnh',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NUMERO COM',
		name: 'numeroCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NOME PAI',
		name: 'nomePai',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NOME MAE',
		name: 'nomeMae',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NOME EMPREGADOR',
		name: 'nomeEmpregador',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NOME CONJUGE',
		name: 'nomeConjuge',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NOME COMPLETO',
		name: 'nomeCompleto',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NATUREZA OCUPACAO',
		name: 'naturezaOcupacao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NATURALIDADE',
		name: 'naturalidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'NACIONALIDADE',
		name: 'nacionalidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'LOGRADOURO RES',
		name: 'logradouroRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'LOGRADOURO COM',
		name: 'logradouroCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'ESTADO CIVIL',
		name: 'estadoCivil',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DDD RES',
		name: 'dddRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DDD COM',
		name: 'dddCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DDD CEL',
		name: 'dddCel',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DATA NASCIMENTO CONJUGE',
		name: 'dataNascimentoConjuge',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DATA NASCIMENTO',
		name: 'dataNascimento',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'DATA EXPEDICAO RG',
		name: 'dataExpedicaoRg',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CPF CONJUGE',
		name: 'cpfConjuge',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'COMPLEMENTO RES',
		name: 'complementoRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'COMPLEMENTO COM',
		name: 'complementoCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CIDADE RES',
		name: 'cidadeRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CIDADE COM',
		name: 'cidadeCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CEP RES',
		name: 'cepRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CEP COM',
		name: 'cepCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'BANCO',
		name: 'banco',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'BAIRRO RES',
		name: 'bairroRes',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'BAIRRO COM',
		name: 'bairroCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'AGENCIA',
		name: 'agencia',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V SEXO',
		name: 'vSexo',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V RG',
		name: 'vRg',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V RENDA',
		name: 'vRenda',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V PATRIMONIO',
		name: 'vPatrimonio',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V PAI',
		name: 'vPai',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V OCUPACAO',
		name: 'vOcupacao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V NOME',
		name: 'vNome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V NATUREZA OCUPACAO',
		name: 'vNaturezaOcupacao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V NATURALIDADE',
		name: 'vNaturalidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V NASCTO',
		name: 'vNascto',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V NACIONALIDADE',
		name: 'vNacionalidade',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V MAE',
		name: 'vMae',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V FONE RESID',
		name: 'vFoneResid',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V ESTADO CIVIL',
		name: 'vEstadoCivil',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V END COM',
		name: 'vEndCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V EMPREGADOR',
		name: 'vEmpregador',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V EMAIL',
		name: 'vEmail',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V CPF',
		name: 'vCpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V CONJUGE NOME',
		name: 'vConjugeNome',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V CONJUGE NASCTO',
		name: 'vConjugeNascto',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V CONJUGE CPF',
		name: 'vConjugeCpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V CNH',
		name: 'vCnh',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V ALERTA',
		name: 'vAlerta',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'CPF',
		name: 'cpf',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'AMBIENTE',
		name: 'ambiente',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
		required: true,
	},
	{
		displayName: 'USUARIO HOMOLOGACAO',
		name: 'usuarioHomologacao',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V END RESID',
		name: 'vEndResid',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V FONE CEL',
		name: 'vFoneCel',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
	{
		displayName: 'V FONE COM',
		name: 'vFoneCom',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['brain'], operation: ['callback_brain'] } },
	},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = this.getNodeParameter('webhookUrl', i) as string;
	const parametros: IDataObject = {
		usuario: this.getNodeParameter('usuario', i) as string,
		senha: this.getNodeParameter('senha', i) as string,
		EMAIL: this.getNodeParameter('email', i) as string,
		CPF_V_CONTEXTO: this.getNodeParameter('cpfVContexto', i) as string,
		CPF_V_INPUT: this.getNodeParameter('cpfVInput', i) as string,
		IDWORKPROCESSO_INPUT: this.getNodeParameter('idworkprocessoInput', i) as string,
		TICKET_INPUT: this.getNodeParameter('ticketInput', i) as string,
		HASH_INPUT: this.getNodeParameter('hashInput', i) as string,
		VALOR_PATRIMONIO: this.getNodeParameter('valorPatrimonio', i) as string,
		UF_RG: this.getNodeParameter('ufRg', i) as string,
		UF_RES: this.getNodeParameter('ufRes', i) as string,
		UF_COM: this.getNodeParameter('ufCom', i) as string,
		TELEFONE_RES: this.getNodeParameter('telefoneRes', i) as string,
		TELEFONE_COM: this.getNodeParameter('telefoneCom', i) as string,
		TELEFONE_CEL: this.getNodeParameter('telefoneCel', i) as string,
		SEXO: this.getNodeParameter('sexo', i) as string,
		RENDA: this.getNodeParameter('renda', i) as string,
		PROFISSAO: this.getNodeParameter('profissao', i) as string,
		ORGAO_RG: this.getNodeParameter('orgaoRg', i) as string,
		NUMERO_SEGURANCA_CNH: this.getNodeParameter('numeroSegurancaCnh', i) as string,
		NUMERO_RG: this.getNodeParameter('numeroRg', i) as string,
		NUMERO_RES: this.getNodeParameter('numeroRes', i) as string,
		NUMERO_REGISTRO_CNH: this.getNodeParameter('numeroRegistroCnh', i) as string,
		NUMERO_COM: this.getNodeParameter('numeroCom', i) as string,
		NOME_PAI: this.getNodeParameter('nomePai', i) as string,
		NOME_MAE: this.getNodeParameter('nomeMae', i) as string,
		NOME_EMPREGADOR: this.getNodeParameter('nomeEmpregador', i) as string,
		NOME_CONJUGE: this.getNodeParameter('nomeConjuge', i) as string,
		NOME_COMPLETO: this.getNodeParameter('nomeCompleto', i) as string,
		NATUREZA_OCUPACAO: this.getNodeParameter('naturezaOcupacao', i) as string,
		NATURALIDADE: this.getNodeParameter('naturalidade', i) as string,
		NACIONALIDADE: this.getNodeParameter('nacionalidade', i) as string,
		LOGRADOURO_RES: this.getNodeParameter('logradouroRes', i) as string,
		LOGRADOURO_COM: this.getNodeParameter('logradouroCom', i) as string,
		ESTADO_CIVIL: this.getNodeParameter('estadoCivil', i) as string,
		DDD_RES: this.getNodeParameter('dddRes', i) as string,
		DDD_COM: this.getNodeParameter('dddCom', i) as string,
		DDD_CEL: this.getNodeParameter('dddCel', i) as string,
		DATA_NASCIMENTO_CONJUGE: this.getNodeParameter('dataNascimentoConjuge', i) as string,
		DATA_NASCIMENTO: this.getNodeParameter('dataNascimento', i) as string,
		DATA_EXPEDICAO_RG: this.getNodeParameter('dataExpedicaoRg', i) as string,
		CPF_CONJUGE: this.getNodeParameter('cpfConjuge', i) as string,
		COMPLEMENTO_RES: this.getNodeParameter('complementoRes', i) as string,
		COMPLEMENTO_COM: this.getNodeParameter('complementoCom', i) as string,
		CIDADE_RES: this.getNodeParameter('cidadeRes', i) as string,
		CIDADE_COM: this.getNodeParameter('cidadeCom', i) as string,
		CEP_RES: this.getNodeParameter('cepRes', i) as string,
		CEP_COM: this.getNodeParameter('cepCom', i) as string,
		BANCO: this.getNodeParameter('banco', i) as string,
		BAIRRO_RES: this.getNodeParameter('bairroRes', i) as string,
		BAIRRO_COM: this.getNodeParameter('bairroCom', i) as string,
		AGENCIA: this.getNodeParameter('agencia', i) as string,
		V_SEXO: this.getNodeParameter('vSexo', i) as string,
		V_RG: this.getNodeParameter('vRg', i) as string,
		V_RENDA: this.getNodeParameter('vRenda', i) as string,
		V_PATRIMONIO: this.getNodeParameter('vPatrimonio', i) as string,
		V_PAI: this.getNodeParameter('vPai', i) as string,
		V_OCUPACAO: this.getNodeParameter('vOcupacao', i) as string,
		V_NOME: this.getNodeParameter('vNome', i) as string,
		V_NATUREZA_OCUPACAO: this.getNodeParameter('vNaturezaOcupacao', i) as string,
		V_NATURALIDADE: this.getNodeParameter('vNaturalidade', i) as string,
		V_NASCTO: this.getNodeParameter('vNascto', i) as string,
		V_NACIONALIDADE: this.getNodeParameter('vNacionalidade', i) as string,
		V_MAE: this.getNodeParameter('vMae', i) as string,
		V_FONE_RESID: this.getNodeParameter('vFoneResid', i) as string,
		V_ESTADO_CIVIL: this.getNodeParameter('vEstadoCivil', i) as string,
		V_END_COM: this.getNodeParameter('vEndCom', i) as string,
		V_EMPREGADOR: this.getNodeParameter('vEmpregador', i) as string,
		V_EMAIL: this.getNodeParameter('vEmail', i) as string,
		V_CPF: this.getNodeParameter('vCpf', i) as string,
		V_CONJUGE_NOME: this.getNodeParameter('vConjugeNome', i) as string,
		V_CONJUGE_NASCTO: this.getNodeParameter('vConjugeNascto', i) as string,
		V_CONJUGE_CPF: this.getNodeParameter('vConjugeCpf', i) as string,
		V_CNH: this.getNodeParameter('vCnh', i) as string,
		V_ALERTA: this.getNodeParameter('vAlerta', i) as string,
		CPF: this.getNodeParameter('cpf', i) as string,
		AMBIENTE: this.getNodeParameter('ambiente', i) as string,
		USUARIO_HOMOLOGACAO: this.getNodeParameter('usuarioHomologacao', i) as string,
		V_END_RESID: this.getNodeParameter('vEndResid', i) as string,
		V_FONE_CEL: this.getNodeParameter('vFoneCel', i) as string,
		V_FONE_COM: this.getNodeParameter('vFoneCom', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'callback_brain',
		parametros,
		webhookUrl,
	});
}
